#!/bin/bash

set -eu

WORKING_DIR=${WORKING_DIR:-"$HOME/code/openstack"}
WORKING_DIR_USER=$(stat -c "%U" $HOME)
VENV_DIR=${VENV_DIR:-"$HOME/venvs/openstack"}
TRACE=${TRACE:-"0"}
SCRIPT_DIR=$(realpath $(dirname $0))

if [ "$TRACE" -eq "1" ]; then
    set -x
fi

function instrpm {
    echo "* Checking for $1"
    if ! rpm -q --whatprovides $1; then
        echo "** Installing $1"
        sudo dnf -y install $1
    fi
}

function delrpm {
    echo "* Checking for $1"
    if rpm -q $1; then
        echo "** Uninstalling $1"
        sudo dnf erase -y $1
    fi
}

function delrpmnodeps {
    echo "* Checking for $1"
    if rpm -q $1; then
        echo "** RPM erasing with --nodeps $1"
        sudo rpm -evh --nodeps $1
    fi
}

instrpm vim-enhanced
instrpm git
instrpm gcc
instrpm python3-devel
instrpm bash-completion
instrpm which
instrpm findutils
instrpm iproute
instrpm python3-setuptools
instrpm python3-requests

# delrpm python3-pip

mkdir -p $WORKING_DIR
pushd $WORKING_DIR

if grep -q -i centos /etc/os-release; then
    if [ ! -d tripleo-repos ]; then
        git clone https://git.openstack.org/openstack/tripleo-repos
    fi

    pushd tripleo-repos
    sudo python3 setup.py install
    popd
    if ! grep -q -i stream /etc/os-release; then
        NO_STREAM="--no-stream"
    else
        NO_STREAM=""
    fi
    sudo /usr/local/bin/tripleo-repos current-tripleo-dev $NO_STREAM
fi

# Clean up symlinked dirs from previous run
sudo rm -rf /usr/share/tripleo-common
echo "* Installing ansible"
instrpm ansible

if [ ! -d python-tripleoclient ]; then
    echo "* Cloning python-tripleoclient because it does not exist in $WORKING_DIR"
	git clone https://opendev.org/openstack/python-tripleoclient
fi
if [ ! -d tripleo-common ]; then
    echo "* Cloning tripleo-common because it does not exist in $WORKING_DIR"
	git clone https://opendev.org/openstack/tripleo-common
fi
if [ ! -d tripleo-ansible ]; then
    echo "* Cloning tripleo-ansible because it does not exist in $WORKING_DIR"
	git clone https://opendev.org/openstack/tripleo-ansible
fi
if [ ! -d tripleo-heat-templates ]; then
    echo "* Cloning tripleo-heat-templates because it does not exist in $WORKING_DIR"
	git clone https://opendev.org/openstack/tripleo-heat-templates
fi
popd

pushd ~
echo "* Checking for pip"
PYTHON_MINOR_VERSION=$(python3 -c "import sys; print(sys.version_info.minor)")
if [ ${PYTHON_MINOR_VERSION} = "6" ]; then
    PIP_URL=https://bootstrap.pypa.io/pip/3.6/get-pip.py
else
    PIP_URL=https://bootstrap.pypa.io/get-pip.py
fi

if [ ! -f /usr/local/bin/pip ]; then
	echo "** Downloading and installing pip"
    curl -L -O ${PIP_URL} && sudo python3 get-pip.py
else
	echo "** Pip already installed"
fi
popd

if ! /usr/local/bin/pip show virtualenv; then
	echo "* Installing virtualenv"
    sudo /usr/local/bin/pip install virtualenv
fi
if ! /usr/local/bin/pip show epdb; then
	echo "* Installing epdb"
    sudo /usr/local/bin/pip install epdb
fi

sudo rm -rf /usr/share/python-tripleoclient
sudo mkdir -p /usr/share/python-tripleoclient
sudo ln -s $WORKING_DIR/python-tripleoclient/templates /usr/share/python-tripleoclient/templates

sudo rm -rf /usr/share/tripleo-common
sudo mkdir -p /usr/share/tripleo-common
sudo ln -s $WORKING_DIR/tripleo-common/container-images /usr/share/tripleo-common
sudo ln -s $WORKING_DIR/tripleo-common/healthcheck /usr/share/tripleo-common
sudo ln -s $WORKING_DIR/tripleo-common/heat_docker_agent /usr/share/tripleo-common
sudo ln -s $WORKING_DIR/tripleo-common/image-yaml /usr/share/tripleo-common
sudo ln -s $WORKING_DIR/tripleo-common/sudoers /usr/share/tripleo-common

site_pkgs=$(python3 -c "import site; print(site.getsitepackages()[0])")
sudo mkdir -p $site_pkgs

sudo rm -rf $site_pkgs/tripleoclient
sudo ln -s $WORKING_DIR/python-tripleoclient/tripleoclient $site_pkgs/tripleoclient
pushd $WORKING_DIR/python-tripleoclient
rm -rf build
python3 setup.py build
popd
echo $WORKING_DIR/python-tripleoclient | sudo tee $site_pkgs/python-tripleoclient.egg-link
sudo rm -rf $site_pkgs/python_tripleoclient.egg-info
sudo ln -s $WORKING_DIR/python-tripleoclient/python_tripleoclient.egg-info $site_pkgs/

sudo rm -rf $site_pkgs/tripleo_common
sudo ln -s $WORKING_DIR/tripleo-common/tripleo_common $site_pkgs/tripleo_common
pushd $WORKING_DIR/tripleo-common
rm -rf build
python3 setup.py build
popd
echo $WORKING_DIR/tripleo-common | sudo tee $site_pkgs/tripleo-common.egg-link
sudo rm -rf $site_pkgs/tripleo_common.egg-info
sudo ln -s $WORKING_DIR/tripleo-common/tripleo_common.egg-info $site_pkgs/

sudo rm -rf /usr/share/openstack-tripleo-heat-templates
sudo ln -s $WORKING_DIR/tripleo-heat-templates /usr/share/openstack-tripleo-heat-templates

${SCRIPT_DIR}/tripleo-dev-symlink-tripleo-ansible

if [ ! -d $VENV_DIR ]; then
    echo "* Creating $VENV_DIR"
    mkdir -p $VENV_DIR
    virtualenv --system-site-packages $VENV_DIR
    echo "** pip installing fixtures/greenlet for deps"
    $VENV_DIR/bin/pip install fixtures greenlet
    echo "** pip installing openstackclient"
    $VENV_DIR/bin/pip install openstackclient
    echo "** pip installing tripleoclient requirements"
    $VENV_DIR/bin/pip install -r $WORKING_DIR/python-tripleoclient/requirements.txt
    echo "** pip installing tripleo-common requirements"
    $VENV_DIR/bin/pip install -r $WORKING_DIR/tripleo-common/requirements.txt
fi


echo "** Symlinking /usr/bin/openstack"
sudo ln -sf $VENV_DIR/bin/openstack /usr/bin/

echo "* Creating $VENV_DIR/share/tripleo-common"
sudo rm -rf $VENV_DIR/share/tripleo-common
sudo mkdir -p $VENV_DIR/share/tripleo-common
echo "** Symlinking $VENV_DIR/share/tripleo-common/container-images"
sudo ln -s $WORKING_DIR/tripleo-common/container-images $VENV_DIR/share/tripleo-common
echo "** Symlinking $VENV_DIR/share/tripleo-common/healthcheck"
sudo ln -s $WORKING_DIR/tripleo-common/healthcheck $VENV_DIR/share/tripleo-common
echo "** Symlinking $VENV_DIR/share/tripleo-common/heat_docker_agent"
sudo ln -s $WORKING_DIR/tripleo-common/heat_docker_agent $VENV_DIR/share/tripleo-common
echo "** Symlinking $VENV_DIR/share/tripleo-common/image-yaml"
sudo ln -s $WORKING_DIR/tripleo-common/image-yaml $VENV_DIR/share/tripleo-common
echo "** Symlinking $VENV_DIR/share/tripleo-common/sudoers"
sudo ln -s $WORKING_DIR/tripleo-common/sudoers $VENV_DIR/share/tripleo-common

if [ ! -f /etc/bash_completion.d/openstack ]; then
    set +o pipefail
    echo "* Running openstack complete"
    $VENV_DIR/bin/openstack complete | grep -v osc_lib | sudo tee /etc/bash_completion.d/openstack
    source /etc/bash_completion.d/openstack
    source /etc/profile.d/bash_completion.sh
    set -o pipefail
fi

echo "* Backing up and removing ~/tripleo-heat-templates"
if [ -d ~/tripleo-heat-templates ]; then
    if [ ! -d ~/tripleo-heat-templates.save ]; then
        mv ~/tripleo-heat-templates ~/tripleo-heat-templates.save
    fi
    rm -rf ~/tripleo-heat-templates
fi
echo "* Symlinking ~/tripleo-heat-templates to $WORKING_DIR/tripleo-heat-templates"
ln -s -f $WORKING_DIR/tripleo-heat-templates ~/tripleo-heat-templates

if [ -d ~${WORKING_DIR_USER}/.local ]; then
    echo "* chown ~${WORKING_DIR_USER}/.local to $WORKING_DIR_USER"
    sudo -E chown -R $WORKING_DIR_USER: ~${WORKING_DIR_USER}/.local
fi

ctlplane_hostname=$(hostname -s).ctlplane
if ! grep $ctlplane_hostname /etc/hosts; then
    echo "127.0.0.1 ${ctlplane_hostname}" | sudo tee -a /etc/hosts
fi

echo "DONE."
