#!/bin/bash

set -eu

WORKING_DIR=${WORKING_DIR:-"$HOME/code/openstack"}
WORKING_DIR_USER=$(stat -c "%U" $HOME)
TRACE=${TRACE:-"0"}
REPOS=${REPOS:-"0"}
SCRIPT_DIR=$(realpath $(dirname $0))

if [ "$TRACE" -eq "1" ]; then
    set -x
fi

function instrpm {
    echo "* Checking for $@"
    if ! rpm -q --whatprovides $@; then
        echo "** Installing $@"
        sudo dnf -y install $@
    fi
}

function delrpm {
    echo "* Checking for $1"
    if rpm -q $1; then
        echo "** Uninstalling $1"
        sudo dnf erase -y $1
    fi
}

function delrpmnodeps {
    echo "* Checking for $1"
    if rpm -q $1; then
        echo "** RPM erasing with --nodeps $1"
        sudo rpm -evh --nodeps $1
    fi
}

source /etc/os-release

if [ "${REPOS}" -ne "0" ]; then
    ${SCRIPT_DIR}/tripleo-dev-tripleo-repos
fi

instrpm python3-tripleoclient openstack-tripleo-common tripleo-ansible
instrpm vim-enhanced
instrpm git
instrpm gcc
instrpm python3-devel
instrpm bash-completion
instrpm which
instrpm findutils
instrpm iproute
instrpm python3-setuptools
instrpm python3-requests

delrpm python3-pip
delrpmnodeps python3-tripleoclient openstack-tripleo-common tripleo-ansible

# Clean up symlinked dirs from previous run
sudo rm -rf /usr/share/tripleo-common
echo "* Installing ansible"
if [ "${VERSION}" -eq "9" ]; then
    instrpm ansible-core ansible-collection-ansible-posix ansible-collection-containers-podman
else
    instrpm ansible
fi


${SCRIPT_DIR}/tripleo-dev-clone

pushd ~
echo "* Checking for pip"
PYTHON_MINOR_VERSION=$(python3 -c "import sys; print(sys.version_info.minor)")
if [ ${PYTHON_MINOR_VERSION} = "6" ]; then
    PIP_URL=https://bootstrap.pypa.io/pip/3.6/get-pip.py
else
    PIP_URL=https://bootstrap.pypa.io/get-pip.py
fi

if [ ! -f /usr/local/bin/pip ]; then
	echo "** Downloading and installing pip"
    curl -L -O ${PIP_URL} && sudo python3 get-pip.py
else
	echo "** Pip already installed"
fi
popd

if ! /usr/local/bin/pip show virtualenv; then
	echo "* Installing virtualenv"
    sudo /usr/local/bin/pip install virtualenv
fi
if ! /usr/local/bin/pip show epdb; then
	echo "* Installing epdb"
    sudo /usr/local/bin/pip install epdb
fi

sudo rm -rf /usr/share/python-tripleoclient
sudo mkdir -p /usr/share/python-tripleoclient
sudo ln -s $WORKING_DIR/python-tripleoclient/templates /usr/share/python-tripleoclient/templates

sudo rm -rf /usr/share/tripleo-common
sudo mkdir -p /usr/share/tripleo-common
sudo ln -s $WORKING_DIR/tripleo-common/container-images /usr/share/tripleo-common
sudo ln -s $WORKING_DIR/tripleo-common/healthcheck /usr/share/tripleo-common
sudo ln -s $WORKING_DIR/tripleo-common/heat_docker_agent /usr/share/tripleo-common
sudo ln -s $WORKING_DIR/tripleo-common/image-yaml /usr/share/tripleo-common
sudo ln -s $WORKING_DIR/tripleo-common/sudoers /usr/share/tripleo-common

site_pkgs=$(python3 -c "import site; print(site.getsitepackages()[0])")
sudo mkdir -p $site_pkgs

sudo rm -rf $site_pkgs/tripleoclient
sudo ln -s $WORKING_DIR/python-tripleoclient/tripleoclient $site_pkgs/tripleoclient
pushd $WORKING_DIR/python-tripleoclient
rm -rf build
python3 setup.py build
popd
echo $WORKING_DIR/python-tripleoclient | sudo tee $site_pkgs/python-tripleoclient.egg-link
sudo rm -rf $site_pkgs/python_tripleoclient.egg-info
sudo ln -s $WORKING_DIR/python-tripleoclient/python_tripleoclient.egg-info $site_pkgs/

sudo rm -rf $site_pkgs/tripleo_common
sudo ln -s $WORKING_DIR/tripleo-common/tripleo_common $site_pkgs/tripleo_common
pushd $WORKING_DIR/tripleo-common
rm -rf build
python3 setup.py build
popd
echo $WORKING_DIR/tripleo-common | sudo tee $site_pkgs/tripleo-common.egg-link
sudo rm -rf $site_pkgs/tripleo_common.egg-info
sudo ln -s $WORKING_DIR/tripleo-common/tripleo_common.egg-info $site_pkgs/

sudo rm -rf /usr/share/openstack-tripleo-heat-templates
sudo ln -s $WORKING_DIR/tripleo-heat-templates /usr/share/openstack-tripleo-heat-templates

${SCRIPT_DIR}/tripleo-dev-symlink-tripleo-ansible

if [ ! -f /etc/bash_completion.d/openstack ]; then
    set +o pipefail
    echo "* Running openstack complete"
    openstack complete | grep -v osc_lib | sudo tee /etc/bash_completion.d/openstack
    source /etc/bash_completion.d/openstack
    source /etc/profile.d/bash_completion.sh
    set -o pipefail
fi

echo "* Backing up and removing ~/tripleo-heat-templates"
if [ -d ~/tripleo-heat-templates ]; then
    if [ ! -d ~/tripleo-heat-templates.save ]; then
        mv ~/tripleo-heat-templates ~/tripleo-heat-templates.save
    fi
    rm -rf ~/tripleo-heat-templates
fi
echo "* Symlinking ~/tripleo-heat-templates to $WORKING_DIR/tripleo-heat-templates"
ln -s -f $WORKING_DIR/tripleo-heat-templates ~/tripleo-heat-templates

if [ -d ~${WORKING_DIR_USER}/.local ]; then
    echo "* chown ~${WORKING_DIR_USER}/.local to $WORKING_DIR_USER"
    sudo -E chown -R $WORKING_DIR_USER: ~${WORKING_DIR_USER}/.local
fi

ctlplane_hostname=$(hostname -s).ctlplane
if ! grep $ctlplane_hostname /etc/hosts; then
    echo "127.0.0.1 ${ctlplane_hostname}" | sudo tee -a /etc/hosts
fi

echo "DONE."
