#!/bin/bash

set -eu

WORKING_DIR=${WORKING_DIR:-"$HOME/code/openstack"}
WORKING_DIR_USER=$(stat -c "%U" $HOME)
VENV_DIR=${VENV_DIR:-"$HOME/venvs/openstack"}
TRACE=${TRACE:-"0"}
SCRIPT_DIR=$(realpath $(dirname $0))

if [ "$TRACE" -eq "1" ]; then
    set -x
fi

echo "* Symlinking tripleo-ansible playbooks..."
sudo rm -rf /usr/share/ansible/tripleo-playbooks
sudo mkdir -p /usr/share/ansible
sudo ln -sf $WORKING_DIR/tripleo-ansible/tripleo_ansible/playbooks /usr/share/ansible/tripleo-playbooks

echo "* Symlinking tripleo-ansible roles..."
sudo mkdir -p /usr/share/ansible/roles
for r in $WORKING_DIR/tripleo-ansible/tripleo_ansible/roles/*; do
    echo "** Symlinking /usr/share/ansible/roles/$(basename $r)"
    sudo rm -rf /usr/share/ansible/roles/$(basename $r)
    sudo ln -sf $r /usr/share/ansible/roles/
done

echo "* Symlinking ansible-role-* roles..."
sudo mkdir -p /usr/share/ansible/roles
for r in $WORKING_DIR/ansible-role-*; do
    role=$(echo $(basename $r) | sed 's/ansible-role-//')
    echo "** Symlinking /usr/share/ansible/roles/$role)"
    sudo rm -rf /usr/share/ansible/roles/$role
    sudo ln -sf $r /usr/share/ansible/roles/$role
done

echo "* Symlinking tripleo-ansible plugins..."
sudo mkdir -p /usr/share/ansible/plugins
for d in $WORKING_DIR/tripleo-ansible/tripleo_ansible/ansible_plugins/*; do
    sudo mkdir -p /usr/share/ansible/plugins/$(basename $d)
    for p in $d/*; do
        echo "** Symlinking /usr/share/ansible/plugins/$(basename $d)/$(basename $p)"
        sudo rm -rf /usr/share/ansible/plugins/$(basename $d)/$(basename $p)
        sudo ln -sf $p /usr/share/ansible/plugins/$(basename $d)/
    done
done

echo "* Symlinking ansible.module_utils.tripleo_common_utils..."
ansible_path=$(python3 -c "import ansible; print(ansible.__path__[0])")
sudo ln -s -f $WORKING_DIR/tripleo-ansible/tripleo_ansible/ansible_plugins/module_utils/tripleo_common_utils.py $ansible_path/module_utils/
